version: '2'

services:
  react:
    image: mhart/alpine-node:8
    volumes:
      - ./react-frontend:/app
    ports:
      - "3030:3000"
    depends_on:
      - mongo
    command: sh -c "cd /app && pwd && npm start"
  mongo:
    image: mongo:3.5
    volumes:
      - ./mongodb_data:/data/db
